name = "default"

[[permissions]]
permission = "madparticle.commands.mp_demo"
value = true

[[permissions]]
permission = "teaconhailuoutil.go"
value = true

[[permissions]]
permission = "voteme.create"
value = false

[[permissions]]
permission = "voteme.create.counter"
value = false

[[permissions]]
permission = "voteme.modify"
value = false

[[permissions]]
permission = "voteme.modify.counter"
value = false
